services:
  node-build:
    container_name: 'AminZabardast.com'
    image: 'aminzabardast/personal-website'
    build: .
    ports:
      - 8148:8080
    environment:
      - PRODUCTION=true # Change to `false` for Development
    # volumes: # Enable for Development
    #   - ./server/app:/code/app
    restart: 'always'
